apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    dew.ms/git-commit: "@ignore@"
    dew.ms/scm-url: "@ignore@"
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    app: kernel
    provider: dew
    version: "@ignore@"
    group: ms.dew.devops.it
  name: kernel
  namespace: dew-prod
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kernel
      group: ms.dew.devops.it
  template:
    metadata:
      annotations:
        dew.ms/git-commit: "@ignore@"
        dew.ms/scm-url: "@ignore@"
        sidecar.jaegertracing.io/inject: 'true'
      labels:
        app: kernel
        provider: dew
        version: "@ignore@"
        group: ms.dew.devops.it
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: ' -Dspring.profiles.active=prod -Dserver.port=8080 -Dopentracing.jaeger.log-spans=false
            -Dopentracing.jaeger.probabilistic-sampler.sampling-rate=0.1 -Dmanagement.endpoints.web.exposure.include=*
            -Dmetrics.tags:application=${spring.application.name}'
        image: "@ignore@"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
        name: dew-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          limits:
            memory: 1Gi
            cpu: 800m
          requests: {}
      nodeSelector:
        group: app
